name: streamdeck
description: A Dart package for building plugins for the Elgato Stream Deck in Dart.
version: 0.4.1
repository: https://github.com/DanTup/streamdeck.dart

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  logging: ^1.3.0
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.3.2

